from oge_py import OGEEnvCfg

env_cfg = OGEEnvCfg(
    random_seed=10,
    sma_base=42164.0,
    ecc_base=0.0,
    incl_base=0.0,
    RA_base=0.0,
    w_base=0.0,
    TA_base=0.0,
    dv_init_red=2.0,
    dv_init_blue=0.2,
    dv_max_per_step_red=0.05,
    dv_max_per_step_blue=0.01,
    capture_distance=30.0,
    timestep=60.0,
    terminal_time=3600.0,
    sma_perturb_max=10.0,
    dist_init_offset_min=90.0,
    dist_init_offset_max=100.0,
    reward_time_weight=-0.05,
    reward_formation_weight=0.04,
    reward_fuel_weight=-0.2,
    reward_capture_weight=10.0,
    reward_timeout_weight=-2.0,
    reward_fuelout_weight=-1.0,
    reward_phase_dist_weight=1.0,
    reward_far_sma_penalty_scale=10.0,
    reward_far_drift_scale=5.0,
    reward_far_drift_max=2.0,
    reward_far_angle_weight=0.5,
    reward_near_energy_scale=10.0,
    reward_near_energy_weight=0.05,
    reward_dist_capture_bonus=0.1,
    reward_dist_min=-1.0,
    reward_alpha_scale=1.0,
)